version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/c/contactvault/Gemfile"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
